Repository aws-solutions/fhir-works-on-aws, pull requests merged in 2023-05, with the labels that each got.

#159 chore: Add environment to gh workflows
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/branch-protection.yml
  .github/workflows/build-test-coverage.yml
  .github/workflows/cfn-analysis.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-smart.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labeler.yml
  .github/workflows/lint-pr.yml
  .github/workflows/merge-develop-to-stage.yml
  .github/workflows/no-response.yaml
  .github/workflows/pnpm-audit-periodically-with-notification.yml
  .github/workflows/pnpm-audit-pr.yml
  .github/workflows/publish-and-merge-to-develop.yml
  .github/workflows/smart-integ-inferno-test-periodically.yaml
  .github/workflows/solutions-pipeline.yml
  .github/workflows/solutions-pull-request.yml
  .github/workflows/verify-changes.yml
Labels: size/s

#158 feat: migration export script
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-tools/package.json
  fwoa-tools/src/export-script.py
  fwoa-tools/src/exportHelper.ts
  fwoa-tools/src/migrationExport.ts
  fwoa-tools/src/migrationUtils.ts
  fwoa-tools/tsconfig.json
Labels: size/l

#161 feat: migration import script
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-tools/.gitignore
  fwoa-tools/package.json
  fwoa-tools/src/exportHelper.ts
  fwoa-tools/src/migrationExport.ts
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationUtils.ts
Labels: size/m

#163 fix: object ownership update
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/branch-protection.yml
  .github/workflows/build-test-coverage.yml
  .github/workflows/cfn-analysis.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-smart.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labeler.yml
  .github/workflows/lint-pr.yml
  .github/workflows/merge-develop-to-stage.yml
  .github/workflows/no-response.yaml
  .github/workflows/pnpm-audit-periodically-with-notification.yml
  .github/workflows/pnpm-audit-pr.yml
  .github/workflows/publish-and-merge-to-develop.yml
  .github/workflows/smart-integ-inferno-test-periodically.yaml
  .github/workflows/solutions-pipeline.yml
  .github/workflows/solutions-pull-request.yml
  .github/workflows/verify-changes.yml
  solutions/smart-deployment/src/lib/bulkExport.ts
  solutions/smart-deployment/src/lib/cdk-infra-stack.ts
  solutions/smart-deployment/src/lib/javaHapiValidator.ts
Labels: size/s

#166 chore: update package versions
  solutions/deployment/lib/cdk-infra-stack.ts
  solutions/deployment/package.json
  solutions/smart-deployment/package.json
  solutions/smart-deployment/src/lib/cdk-infra-stack.ts
Labels: size/xs

#162 feat: binary conversion
  .github/workflows/smart-integ-inferno-test-periodically.yaml
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-tools/src/binaryConverter.ts
  solutions/smart-deployment/src/lib/bulkExport.ts
  solutions/smart-deployment/src/lib/cdk-infra-stack.ts
  solutions/smart-deployment/src/lib/javaHapiValidator.ts
Labels: size/m

#167 docs: update changelogs for S3 objectOwnership
  CHANGELOG.md
  solutions/deployment/CHANGELOG.md
  solutions/smart-deployment/CHANGELOG.md
Labels: size/s

#168 feat: release to main - 5/12/2023
  .github/workflows/smart-integ-inferno-test-periodically.yaml
  CHANGELOG.md
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/deployment/CHANGELOG.md
  solutions/deployment/lib/cdk-infra-stack.ts
  solutions/deployment/package.json
  solutions/smart-deployment/CHANGELOG.md
  solutions/smart-deployment/package.json
  solutions/smart-deployment/src/lib/bulkExport.ts
  solutions/smart-deployment/src/lib/cdk-infra-stack.ts
  solutions/smart-deployment/src/lib/javaHapiValidator.ts
Labels: size/m

#169 test: verification
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-core/authz-smart/package.json
  fwoa-tools/package.json
  fwoa-tools/src/export-script.py
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationUtils.ts
  solutions/deployment/package.json
  solutions/smart-deployment/package.json
Labels: size/m

#171 chore: Increase log retention to 10 years
  solutions/deployment/lib/bulkExportStateMachine.ts
  solutions/deployment/lib/cdk-infra-stack.ts
  solutions/deployment/lib/elasticsearch.ts
  solutions/smart-deployment/src/lib/bulkExportStateMachine.ts
  solutions/smart-deployment/src/lib/cdk-infra-stack.ts
  solutions/smart-deployment/src/lib/elasticsearch.ts
Labels: size/s
