Repository aws-solutions/fhir-works-on-aws, pull requests merged in 2023-07, with the labels that each got.

#205 test: migration export unit test
  fwoa-tools/package.json
  fwoa-tools/src/migrationExport.test.ts
  fwoa-tools/src/migrationExport.ts
Labels: size/m

#206 test: util unit test
  .gitignore
  fwoa-tools/package.json
  fwoa-tools/src/integration-tests/migrationUtilsInteInteg.test.ts
  fwoa-tools/src/migrationExport.ts
  fwoa-tools/src/migrationUtils.test.ts
  fwoa-tools/src/migrationUtils.ts
Labels: size/m

#209 fix: import state file
  fwoa-tools/src/migrationImport.ts
Labels: size/xs

#204 test: unit tests for import and binary conversion
  .gitignore
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-tools/.gitignore
  fwoa-tools/package.json
  fwoa-tools/src/binaryConverter.test.ts
  fwoa-tools/src/binaryConverter.ts
  fwoa-tools/src/migrationImport.test.ts
  fwoa-tools/src/migrationImport.ts
Labels: size/xl

#212 test: add migrationVerify test
  fwoa-tools/src/migrationVerify.test.ts
  fwoa-tools/src/migrationVerify.ts
Labels: size/m

#211 test: unit test for export util
  .gitignore
  fwoa-tools/src/exportHelper.test.ts
Labels: size/m

#213 chore: solutions pipeline related updates
  CHANGELOG.md
  buildspec.yml
  fwoa-tools/config/jest.config.json
Labels: size/s

#208 docs: add FWoA migration guide
  .viperlightignore
  FHIR Works on AWS - Migration Tool User Guide - 05-JUL-2023.pdf
Labels: size/xs

#216 chore: update SonarQube properties
  sonar-project.properties
Labels: size/s

#218 refactor: fix export script cleanliness
  fwoa-tools/src/export-script.py
  solutions/deployment/bulkExport/glueScripts/export-script.py
  solutions/smart-deployment/bulkExport/glueScripts/export-script.py
Labels: size/s

#219 fix: add extended polling time on import
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationUtils.ts
Labels: size/xs

#222 fix: clear appended data
  CHANGELOG.md
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-tools/src/binaryConverter.test.ts
  fwoa-tools/src/binaryConverter.ts
  solutions/deployment/CHANGELOG.md
  solutions/smart-deployment/CHANGELOG.md
Labels: size/s

#225 chore: update package numbers
  solutions/deployment/lib/cdk-infra-stack.ts
  solutions/deployment/package.json
  solutions/smart-deployment/package.json
  solutions/smart-deployment/src/lib/cdk-infra-stack.ts
Labels: size/xs

#226 fix: Update init-auth.py to use user input
  solutions/deployment/scripts/init-auth.py
Labels: size/xs

#227 docs: Update README.md
  solutions/deployment/README.md
Labels: size/xs

#229 chore: release v6.1.1
  CHANGELOG.md
  common/autoinstallers/commitlint/pnpm-lock.yaml
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-tools/src/binaryConverter.test.ts
  fwoa-tools/src/binaryConverter.ts
  solutions/deployment/CHANGELOG.md
  solutions/deployment/README.md
  solutions/deployment/lib/cdk-infra-stack.ts
  solutions/deployment/package.json
  solutions/deployment/scripts/init-auth.py
  solutions/smart-deployment/CHANGELOG.md
  solutions/smart-deployment/package.json
  solutions/smart-deployment/src/lib/cdk-infra-stack.ts
Labels: size/xl
