Repository aws-solutions/fhir-works-on-aws, pull requests merged in 2023-06, with the labels that each got.

#173 test: add integration tests and update license headers
  fwoa-tools/src/binaryConverter.ts
  fwoa-tools/src/createPatientPractitionerEncounterBundle.json
  fwoa-tools/src/export-script.py
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationIntegTests.test.ts
  fwoa-tools/src/migrationUtils.ts
Labels: size/m

#176 fix: binary objects
  fwoa-tools/src/binaryConverter.ts
Labels: size/xs

#177 fix: sorting fix
  .viperlightignore
  fwoa-tools/src/binaryConverter.ts
  fwoa-tools/src/migrationExport.ts
Labels: size/s

#180 chore: update changelog, mfa delete message, and fast-xml-parser version
  CHANGELOG.md
  common/changes/@aws/fhir-works-on-aws-authz-smart/kcadette-docs-changelogs-mfa_2023-06-07-15-15.json
  common/changes/@aws/fhir-works-on-aws-authz-smart/kcadette-docs-changelogs-mfa_2023-06-07-15-24.json
  common/changes/@aws/fhir-works-on-aws-search-es/kcadette-docs-changelogs-mfa_2023-06-07-15-24.json
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-core/search-es/package.json
  solutions/smart-deployment/README.md
Labels: size/s

#181 fix: binary verification
  fwoa-tools/src/migrationUtils.ts
Labels: size/xs

#184 fix: migration export-script performance update
  fwoa-tools/src/export-script.py
Labels: size/m

#185 fix: export script updates
  fwoa-tools/src/binaryConverter.ts
  fwoa-tools/src/exportHelper.ts
  fwoa-tools/src/migrationExport.ts
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationUtils.ts
Labels: size/m

#186 chore: version bumps
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-utilities/package.json
  solutions/deployment/package.json
  solutions/smart-deployment/package.json
Labels: size/m

#188 feat: migration import script updates
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationUtils.ts
Labels: size/m

#191 fix: partition resources by version
  fwoa-tools/src/export-script.py
Labels: size/s

#192 fix: file name restructure updates
  fwoa-tools/src/binaryConverter.ts
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationVerify.ts
Labels: size/s

#193 refactor: centralize configuration check for scripts
  fwoa-tools/src/migrationExport.ts
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationUtils.ts
  fwoa-tools/src/migrationVerify.ts
Labels: size/m

#195 fix: tenantId for import
  fwoa-tools/src/migrationImport.ts
Labels: size/xs

#198 chore: allow running unit tests in fwoa-tools
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  fwoa-tools/config/heft.json
  fwoa-tools/config/jest.config.json
  fwoa-tools/config/rig.json
  fwoa-tools/package.json
  fwoa-tools/src/integration-tests/migrationIntegTests.test.ts
  fwoa-tools/src/integration-tests/migrationUtils.test.ts
Labels: size/xl

#200 refactor: remove unused parameter and function, reorganize function
  fwoa-tools/src/integration-tests/migrationIntegTests.test.ts
  fwoa-tools/src/migrationUtils.ts
  fwoa-tools/src/migrationVerify.ts
Labels: size/m

#201 perf: use bundles for deletion
  fwoa-tools/src/migrationImport.ts
  fwoa-tools/src/migrationUtils.ts
  fwoa-tools/src/migrationVerify.ts
Labels: size/m

#197 fix: include tenantId when import from multitenant
  fwoa-tools/src/migrationImport.ts
Labels: size/s
